### PR TITLE
Fix environment variable naming for RPC URLs

### LINKED ISSUE #95: Make naming consistent with the config generator in `manager-multisig` while generating `example.env` file
The config generator for the merkle funder handler in `manager-multisig` utilizes environment variables for RPC URLs in the template `FUNDER_RPC_URL_<CHAIN-ALIAS>_1` as you can see [here](https://github.com/api3dao/manager-multisig/blob/b975f107707933225171e8b2669193de40115eb8/chain/merkle-funder/scripts/generate-merkle-funder-config.js#L38) however in [this](https://github.com/api3dao/merkle-funder/blob/37aede30c4767a267642fd256027c6067b1019d4/scripts/write-env-example-file.ts#L5) repository it's being generated as `FUNDER_RPC_URL_<CHAIN-ALIAS>`. It makes populating .env file harder and creates a conflict.

### PR DESCRIPTION
**Pull request by bdrhn9**
Closes #95

### CODE REVIEW

**Comment by bbenligiray** [comment]
Wouldn't it make more sense to remove the `_1`?

**Comment by bdrhn9** [comment]
> Wouldn't it make more sense to remove the `_1`?

If we aren't planing to use multiple RPCs, it makes sense more, yes.

**Comment by bbenligiray** [comment]
The current `_1` additions don't make it any easier to use multiple RPCs

**Comment by bdrhn9** [comment]
> The current `_1` additions don't make it any easier to use multiple RPCs

You're right. So fixing [here](https://github.com/api3dao/manager-multisig/blob/b975f107707933225171e8b2669193de40115eb8/chain/merkle-funder/scripts/generate-merkle-funder-config.js#L38) is what you'd prefer?

**Comment by acenolaza** [comment]
Closing PR due to being fixed [here](https://github.com/api3dao/manager-multisig/blob/b975f107707933225171e8b2669193de40115eb8/chain/merkle-funder/scripts/generate-merkle-funder-config.js#L38)

**Pull request closed without merging**
